// Where each dish's photos come from: Wikimedia Commons categories (and their direct sub-categories,
// unless `depth: 0`). Photos are used to build and test the model; they are not shipped with the app.
// Order matters: a photo belongs to the first dish that lists it (palabok comes before pancit, for example).
export const DISH_SOURCES = [
  { id: "adobo", categories: ["Adobo", "Chicken adobo", "Pork adobo"], depth: 0 },
  { id: "sinigang", categories: ["Sinigang"] },
  { id: "kare-kare", categories: ["Kare-kare"] },
  { id: "sisig", categories: ["Sisig"] },
  { id: "lechon", categories: ["Lechon (Filipino cuisine)"] },
  { id: "lechon-kawali", categories: ["Lechon kawali"] },
  { id: "palabok", categories: ["Pancit palabok"] },
  { id: "pancit", categories: ["Pancit"] },
  { id: "lumpia", categories: ["Lumpia"] },
  { id: "halo-halo", categories: ["Halo-halo"] },
  { id: "bibingka", categories: ["Bibingka"], depth: 0 },
  { id: "puto", categories: ["Puto"], depth: 0 },
  { id: "puto-bumbong", categories: ["Puto bumbong"], depth: 0 },
  { id: "tinola", categories: ["Tinola"] },
  { id: "dinuguan", categories: ["Dinuguan"] },
  { id: "pinakbet", categories: ["Pinakbet"] },
  { id: "bicol-express", categories: ["Bicol Express"] },
  { id: "longganisa", categories: ["Longganisa"] },
  { id: "tocino", categories: ["Tocino"] },
  { id: "balut", categories: ["Balut (food)"] },
  { id: "turon", categories: ["Turon (food)"] },
  { id: "banana-cue", categories: ["Banana cue"], depth: 0 },
  { id: "kwek-kwek", categories: ["Tokneneng - Kwek kwek"], depth: 0 },
  { id: "fish-ball", categories: ["Fish balls"] },
  { id: "isaw", categories: ["Isaw"] },
  { id: "ube-halaya", categories: ["Ube halaya"] },
  { id: "kinilaw", categories: ["Kinilaw"] },
  { id: "chicken-inasal", categories: ["Chicken inasal"] },
  { id: "sapin-sapin", categories: ["Sapin-sapin"] },
  { id: "kutsinta", categories: ["Kutsinta", "Puto Kutsinta ng Arayat"] },
  { id: "suman", categories: ["Suman (food)"] },
  { id: "ensaymada", categories: ["Ensaymada (Philippines)"] },
  { id: "pandesal", categories: ["Pandesal"] },
  { id: "champorado", categories: ["Champorado"], depth: 0 },
  { id: "ginataan", categories: ["Ginataan"] },
  { id: "lugaw", categories: ["Lugaw", "Arroz caldo"] },
  { id: "batchoy", categories: ["Batchoy"] },
  { id: "kaldereta", categories: ["Kaldereta"] },
  { id: "menudo", categories: ["Menudo (stew)"] },
];

// Photos of things that are NOT a Filipino dish (other cuisines, and things that aren't food at all), so the
// model can say "I don't think that's a Filipino dish" instead of forcing a guess. Everything with an
// `other-` id is treated as one class.
export const OTHER_SOURCES = [
  { id: "other-pizza", categories: ["Pizza"], depth: 0 },
  { id: "other-sushi", categories: ["Sushi"], depth: 0 },
  { id: "other-hamburger", categories: ["Hamburgers"], depth: 0 },
  { id: "other-salad", categories: ["Salads"], depth: 0 },
  { id: "other-pasta", categories: ["Spaghetti"], depth: 0 },
  { id: "other-steak", categories: ["Steaks"], depth: 0 },
  { id: "other-friedchicken", categories: ["Fried chicken"], depth: 0 },
  { id: "other-tacos", categories: ["Tacos"], depth: 0 },
  { id: "other-ramen", categories: ["Ramen"], depth: 0 },
  { id: "other-sandwich", categories: ["Sandwiches"], depth: 0 },
  { id: "other-cake", categories: ["Cakes"], depth: 0 },
  { id: "other-fruit", categories: ["Fruit"], depth: 0 },
  { id: "other-curry", categories: ["Curry"], depth: 0 },
  { id: "other-cats", categories: ["Cats"], depth: 0 },
  { id: "other-dogs", categories: ["Dogs"], depth: 0 },
  { id: "other-cars", categories: ["Cars"], depth: 0 },
  { id: "other-people", categories: ["Portrait photographs"], depth: 0 },
  { id: "other-landscape", categories: ["Landscapes"], depth: 0 },
];
